### ISSUE TITLE
possible to use this on discord app instead of chrome?

### ISSUE THREAD

**Issue by kamikazilucas** [Multarix/Discord-Hide-Blocked-Messages#4]
i want to use this on the app since i dont use discord on chrome

**Comment by Multarix** [comment]
Press "ctrl + shift + i" to open the console on the app.
It's in the instructions.

**Comment by kamikazilucas** [comment]
How do you save it so it keeps it when you restart discord

**Comment by Multarix** [comment]
You cannot, you have to paste it in every time discord is restarted. Again, this is covered in the instructions. If you wish to have it always active without thought, using a userscript with chrome is your best bet, else never close discord. Otherwise there is nothing I can do to help.
