### ISSUE TITLE
Can no longer open Discord Dev Tools using Command

### ISSUE THREAD

**Issue by Davis24** [Multarix/Discord-Hide-Blocked-Messages#6]
Hi,

Wanted to let you know they remove the ability to open DEV tools. You now need to modify the settings JSON. 

You can see the conversation here: https://www.reddit.com/r/discordapp/comments/sc61n3/comment/hu4fw5x/?utm_source=share&utm_medium=web2x&context=3

**Comment by Multarix** [comment]
Yes, I'm aware, I'll post a warning/ work around
