### ISSUE TITLE
Make the script also remove blocked users in the right members panel/sidebar on a server?

### ISSUE THREAD

**Issue by ghost** [Multarix/Discord-Hide-Blocked-Messages#7]
Script seems to work just fine, I use it in a web browser with violent monkey, I think this would be a nice feature to add though

**Comment by Multarix** [comment]
This seems a bit pointless to me and much harder to do. The way this script currently works is simply by looking for any element that matches, then hiding it. To hide specific users that you block would be much more difficult as it would require looking for the user id in said blocked messages, finding a user that matched, hiding them etc. It doesn't hook into your discord account to find blocked people.
